### ISSUE TITLE
Notification component for Altinn 3

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-notifications#1]
## Description 

Altinn 3 need to be able to notify actors related to instances. This could be the reportee but also users who have roles/rights for the reporter

### Email notification

We need to be able to send email notifications to either a supplied email endpoint or endpoint registered either in [common contact register](https://eid.difi.no/en/common-contact-register) or [Notificaton addresses for enterprises KoFuVi](https://www.brreg.no/en/products-and-services-2/order-products/machine-readable-data-from-the-central-coordinating-register-for-legal-entities/notification-addresses-to-apply-in-public-administration/?nocache=1637776875427)

The email notification will have a body and a header. It also needs to support HTML 

- [ ] The sender can supply e-mail addresses for endpoint
- [ ] Notificaiton can find e-mail addresses from common contact register 
- [ ] Can find e-mail addresses from KoFuVi 
- [ ] Support HTML emails

### SMS Notification

We need to be able to send email notifications to either a supplied email endpoint or endpoint registered either in [common contact register](https://eid.difi.no/en/common-contact-register) or [Notificaton addresses for enterprises KoFuVi](https://www.brreg.no/en/products-and-services-2/order-products/machine-readable-data-from-the-central-coordinating-register-for-legal-entities/notification-addresses-to-apply-in-public-administration/?nocache=1637776875427)

The email notification will have a body and a header. It also needs to support HTML 

- [ ] The sender can supply phone number addresses for endpoint
- [ ] Notification component can find SMS addresses from common contact register 
- [ ] Can find sms addresses from KoFuVi 

### Push Notification

In the future, we might want to push notifications to apps

### Portal Notification

This would be a new concept in Altinn but is a common concept in most major applications like Github. Having a Notification alert in Altinn to present information could be beneficial 

### Logging of notification usage

We need to be able to log usage of notifications to be able to generate reports on email and SMS sending.  

- [ ] It should be possible to create reports on usage of notification

### Authorization & Authentication

We need to authorize the sender.

- [ ] Create Notification endpoint need to require org authentication
- [ ] Create Notification endpoint need to authorize org for sending

### Async 

The Create Notification API needs to be async

### Latest .Net

Use latest .Net 

### Microservice

The notification component needs to be deployed to the platform solution as a docker container

### Core services should be configurable

For the email server we need to build the component in a way that we can replace it with other

**Comment by acn-sbuad** [comment]
All points here are covered by #60. Closing this feature request.
