### ISSUE TITLE
Integrate with storage

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-notifications#10]
## Description

We need to be able to integrate with storage for the following need

- Beeing able to identify instance owner
- Beeing able to verify correct instance id
- Beeing able to authorize the sender
- 
## Consideration
Do we really need to authorize

## Development task
- [ ] Create client for storage
- [ ] Implement code for storage call for instance info

**Comment by SandGrainOne** [comment]
Relevant for a Reminder component.

**Comment by annerisbakk** [comment]
@SandGrainOne Legges i backlog?

**Comment by acn-sbuad** [comment]
Think we can close this given how reminders has been solved with send condition. @olebhansen @SandGrainOne
