### ISSUE TITLE
Analysis: Investigate which email service the notification component should use

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#108]
## Description

A central part of the notification functionality is supported by sending notifications through email. 
For the hackaton we piggybacked of a test e-mail server used widely in the organisation. When implementing the notification functionality now for permament use we should have a separate more stable way of sending emails. 

## In scope
This analysis should research and compare available options considering the following factors: 
- availability (SLAs)
- cost
- fully maintained/need for maintenance
- synergy effects with the rest of the organization
- monitoring opportunities
- Skal en epost med flere mottakere i Til feltet telle som en eller flere eposter?

## Out of scope
- Implementation, new issues should be created for implementation and deployment of the solution that is deemed the best. 

## Tasks
- [ ] Is this issue labeled with a correct area label?
- [ ] QA has been done

## Acceptance criteria
A reccommendation of which email service to use is in place highlighing it's advantages and disadvantages compared to a small number of other services.

**Comment by FinnurO** [comment]
Analysis also relevant for A3 apps sending formdata by mail (Digdir A3 apps, e.g. becoming a service owner)

**Comment by Herskis** [comment]
We now have a testinstance of Azure Communication services, connected with the domain altinn.cloud
It is not yet build with IAC

An example using Azure CLI:
az communication email send --sender "<donotreply@altinn.cloud>" --to "<[eshe@digdir.no](mailto:eshe@digdir.no)>" --subject "Welcome to Azure Communication Services Email" --text "This email message is sent from Azure Communication Services Email using Azure CLI." --connection-string "endpoint=https://altinn-sbl-communication.communication.azure.com/;accesskey=_**Hidden**_"

The service now supports domain altinn.cloud with sender donotreply@altinn.cloud

Priser er som følger:
kr0.00266/Email sent
kr0.00128/MB transferred

The service will also support SMS, but this is still in public preview.

**Comment by annerisbakk** [comment]
Svar fra Sindre Ramung

Vi har diskutert samarbeid / fellesløsning for varsling med Altinn 3-teamet i fjor høst, men konkluderte med at de funksjonelle behovene Altinn har, er såpass mye mer avanserte enn våre, i tillegg til at det er en del tekniske ulikheter mellom Altinn og eID-løsningene våre , at vi mente det ikke var så mye å hente på et videre samarbeid/fellesløsning i denne sammenhengen
Nå handler ikke det om e-post-varsling, men jeg skal likevel legge til at vi ser på Altinn sine muligheter for avrop på SMS-tjenesten vi har i eID sin driftsavtale. Her har det vært en del dialog mellom avtaleforvalterer og produkteiere i BOD og FEL, og det skal være et ikke tidfestet møte mellom Altinn, leverandøren og FEL sin avtaleforvalter forhåpentligvis om ikke så lenge
Men så tilbake til e-post-varsling: MinID og Kontakt- og reservasjonsregisteret, som er tjenestene våre som benytter e-postvarsling, bruker en tjeneste i driftsplattformen. Jeg vil tro dette er en såpass standardisert tjeneste, at Altinn sikkert er bedre tjent med å bruke tilsvarende tjeneste på egen plattform.

@SandGrainOne @acn-sbuad @tba76 @aas-tbuar @Herskis 
Så hvis vi er enige i denne konklusjonen, må vi ta en beslutning på hvilken løsning vi velger å benytte. Jeg kaller inn til møte for å diskutere tema.

**Comment by SandGrainOne** [comment]
We decided to go for Azure Communication services. 
Additional tasks has been added to #148
