### ISSUE TITLE
GetUnsentTargets should accept an input param

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#109]
## Description
Postgre function GetUnsentTargets should accept an input parameter to identify if target types to retrieve is email, sms or both. 

### Ops requirements
Manually update in AT22. And update existing migration script. 

## Acceptance criteria
- Notifications Service adds target type when retrieving unsent targets

## Development tasks
- [ ] Update database function 
- [ ] Update repository class to take input parameter
- [ ] Update notificationsservice to include type
- [ ] Update migration script for generation of function
- [ ] Manual tweaking in database to avoid a new table
- [ ] Manual test

## Test
- [ ] Regression test.

**Comment by SandGrainOne** [comment]
No longer relevant.
