### ISSUE TITLE
Do we continue using functions/proc or rather implement SQL query directly

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#110]
## Your question

We need a decision on whether or not we should continue using functions/proc or rather implement the SQL query directly in repository class 

## Acceptance Criteria

- [ ] Documentation updated with peer-reviewed suggestions

**Comment by SandGrainOne** [comment]
I believe we technically already have "pure" SQL in code. The SQL code is very short and simple because it's performing a call to a function or procedure, but it is technically inline SQL.

**Comment by vgr** [comment]
My proposal for best-practice guidelines for PostgreSQL answers this question indirectly, but:
It is safe to use embedded SQL in C#/Npgsql-commands as long as you
- use *parameters*
- don't concatenate the SQL with user-defined strings (without robust input validation)
- don't call unsafe functions with user-defined parameters

Therefore the recommendation should be to use functions and stored procedures if you need the capabilities they offer (performance, prepared statements, PL, etc), but should not be forced to complicate simple SQL queries that don't have performance requirements.
