### ISSUE TITLE
Write necessary infrastructure code to setup an Azure Communication Services service

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#150]
## Description

The microservice itself will run as a docker container in the platform cluster. 
- It will communicate with the Kafka broker instance both producing and consuming though the _Confluent.Kafka _ package (uses TCP/IP).
- It will connect to Platform key vault to gain access to secrets and certificates.
- It will connect with Azure Communication Services also provisioned in this issue.

Infrastructure will be provisioned through Terraform, and script should be in a seperate state file from other platform components if possible. 

## Considerations
- [ ] What resource group should the communication service be placed in? 
- [ ] Do we need a single instance of communication services per environment or could we share instances in test? How does the number of instances affect cost? 

## Development tasks
- [x] Create a terraform script to set up an Azure Communication Services service
- [ ] Create terraform scripts creating nessesary bindings between email service and other Azure resources. 
- [ ] QA
- [ ] Manual test is complete
- [x] Deploy to all AT environments
- [ ] Deploy to TT/YT
- [ ] Deploy to production 

## Test
- [ ] Verify that microservice starts okay with 2/2 ready state

## Acceptance criteria
- [x] Email microservice is granted access to read from platform key vault
~~- [ ] E-mail microservice is granted access to publish and subscribe from Kafka~~
- [ ] E-mail microservice is granted access to communicate with Azure Communication services
- [ ] Required infrastructure and access grants present in AT
- [ ] Required infrastructure and access grants present in TT/YT
- [ ] Required infrastructure and access grants present in Prod

**Comment by simon-ellefsen** [comment]
Deployed infrastructure to all AT environments + TT02.
TT02 is missing domain settings, Espen knows the procedure for setting this up.
Terraform does not support setting email domains for the communication service, for now it is done manually in the portal.
