### ISSUE TITLE
Analysis: Monitoring of Communication services

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#154]
## Description
How do we best monitor the e-mail solution? 
Where can we have failure and how can we act on these failures.

What requirements do we have to availability of the solution. 

- #160 covers monitoring the connectivity to the Kafka broker
- How to monitor availability of e-mail server? 
- How do we pick up on errors in this component? No incomning API requests

## In scope

- Identify tools for monitoring as well as metrict/telemetry that is relevant. 
- Alert rules should be defined at a high level, but not implemented. 
- Creating development issues that can be implemented at a later point in time

## Out of scope
- Implementation

**Comment by SandGrainOne** [comment]
No longer relevant
