### ISSUE TITLE
Analysis: How to handle potential duplicate reading of a notification from Kafka

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#158]
## Description
We need to ensure that an email isn't sent out multiple times due to errors in the communication between the  email microservice and Kafka. We will have multiple instances of the e-mail microservice representing the same consumer group. How can we ensure that if an email is sent successfully from one instance, that another doesn't attempt to send the same? 

This is considered in relation to an an error flow where a pod is shut down before the call back to Kafka reporting a successful sending of the e-mail is completed. 

Relevant documentation (see section 2):  https://i-topolev-vladimir.medium.com/how-to-handle-duplicate-messages-and-message-ordering-in-kafka-82e2fef82025

## In scope
- Define a strategy for identifying potential duplicate readings and avoiding sending e-mail

### Option: Database to keep track of sendt messages
- Could we have a database or separate storage to keep track of emails
  - Repo on GitHub which describes a similar process: https://github.com/networknt/light-email
  - "Every email event has a unique id and this id will ensure that the same email will only be sent once. When the event sourcing application is replayed, no emails will be sent out, so there are no side effects."

- https://thecloudblog.net/post/building-reliable-kafka-producers-and-consumers-in-net/
- https://cloudinfrastructureservices.co.uk/kafka-best-practices-topic-partitions-consumers-producers-and-brokers/
## Conclusion
Based on various articles we have landed on a set of configurations and practices for both the consumer and producer to ensure as far as we can that we have exactly once processing. 

For the consumer it depends on the criticality of what is done if we need a database table to keep track of which elements have been processed previously and not. To begin with we will have simple mechanisms to encourage exactly once processing. But let us consider to extend in the future with a db table to keep track of processing.

### Consumer
- Manually commit and offset 
            
### Producer 
- Acks is set to Acks.All to ensure that a message has been written to all replicas before we consider it received by the broker
- EnableDeliveryReports is set to `true`. It worsens performance, but we do not want a fire and forget kind of behavior in the producer
- EnableIdempotence is set to true
- On dispose we m cake sure to flush the producer ensuring that we wait for all delivery reports before closing the producer. 
- ProducerService returns a boolean to indicate whether the message was received by the broker or not, so caller can take action

**Comment by SandGrainOne** [comment]
Tiltakene i konklusjon har blitt tatt hensyn til i implementasjon.
