### ISSUE TITLE
Endpoint for Posting a notification order (publish event for immediate sending)

### ISSUE THREAD

**Issue by tba76** [Altinn/altinn-notifications#164]
## Description

Endpoint for posting a notification (syncron) should save to database and push to Kafka-topic.
## Considerations

- Is from address required to provide? What is our default sender? 
-  Is sendersReference required? 
- 
## Specification tasks
- [swagger for  API  ](https://app.swaggerhub.com/apis/STEPHANIEBUADU/Notifications/1.0.0#/EmailNotificationOrderRequest)
## Development tasks
- [x] Create new controller and endpoint for post notification
- [x] Create service for save notification
- [x] Create necessary database tables (procedures, functions?)
- [x] Create repository-classes
~~- [ ] Add authorization to endpoint (ScopeOrAccessToken)~~ should be handled in #8
- [x] Documentation
  - [x] Swagger
- [x] QA
- [x] Manual test is complete (if relevant)

## Acceptance criteria
- [x] Posting a new notification should save to postgres 
- [x] Invalid input should be denied (bad request)
- [x] Unauthorized users should be denied post

**Comment by SandGrainOne** [comment]
[openapi3_1.yaml.txt](https://github.com/Altinn/altinn-notifications/files/11881876/openapi3_1.yaml.txt)
