### ISSUE TITLE
Analysis: Determine how we would like Kafka to be hosted. (Include hardening)

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#167]
## Description
Throughout the organization Kafka is being hosted in different ways. 
FDK is hosting it themselves. 
FEL is buying it as a service from a provider. 

In Altinn we have considered using Apache Kafka on Confluent Cloud in Azure. 
However, FEL opted out from Confluent cloud due to cost. 

We should investigate our options and check if we can use the same service that FEL is using before making a decision. 

## Conclusion
We've decided to go for **Apache Kafka® on Confluent Cloud™** for now.

The initial use will be limited. The should be possible to hold the costs down below 1000$ for quite a while. That's not too bad. We will need to keep track of the cost and reconsider other hosting options in the future.

**Comment by aas-tbuar** [comment]
FEL hoster Kafka ved hjelp av Strimzi operator i Azure (AKS) og i Openshift private cloud (Tieto).
