### ISSUE TITLE
General exceptions not in a http request context are not picked up by any alerts. E.g. logged by kafkaconsumer

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#268]
## Description
Create an alert rule where the query looks at exceptions instead of failed requests. Now that we can have more exceptions being produced by background services we need an alert that can detect them. 

First version of this should be exclusive for notifications and notifications-email. Should be expandable in the future if it's working well.

Consider the need to keep the existing alert on failed requests.

## Alternatives

alt 1 and 2 entails disabling all health checks 

1. Set up a general exception alert. Picks up all exceptions. Will mean removing/replacing the kafka producer specific exception that is in place now
2. Set up a general exception alert + specialized exception alerts for kafka + communication services. 
3. Continue to work on fixing health checks and general instabilities

**Comment by acn-sbuad** [comment]
Due to a high number of exceptions in the logges we have had to clean up these before implementing an alert rule. 
1st: extended timeout for liveness probe to 2 seconds. 
2nd: disables kafka health check

**Comment by acn-sbuad** [comment]
PR: https://dev.azure.com/brreg/altinn-studio-ops/_git/altinn-studio-ops/pullrequest/773
