### ISSUE TITLE
Analyze: Look into using Aiven as a Kafka provider

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#270]
### Description

The cost of Confluent Cloud hit us a bit too hard. We should look into alternatives and see if they can be cheaper. One such provider is [Aiven](https://aiven.io/).

### In scope

Known requirements:
- Secured network, peering for ai-dev
- Cheaper than Confluent Cloud
- More?

**Comment by annerisbakk** [comment]
Lukkes - Kafka skal ikke brukes
