### ISSUE TITLE
What is persisted of notifications in Altinn 2

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#276]
### Description

We are investigating the requirements w.r.t persistence of notifications and which data points we are required to archive and for how long. As input to this work we would like to know: 
-  how the current notification implementation handles persistence of data
- How long data is persisted?
- Which data points are persisted?

Output of this analysis should be passed on to the teams legal coaches as well as shared witht he team.

### In scope

Current procedures for Altinn 2

### Out of scope

Development or analysis of how it should be solved in the new notifications solution

#### Persistence of data
- Standalone notifications (a notification not related to an Altinn service) are deleted immediately after sending 
- Notifications related to an instance of a service are archived and persisted as long as the instance is persisted (the data is required for the activity log)
 - The notifications template is not deleted. 
 - Placeholders to inject into templates are persisted as long as the notification is persisted. 
 

#### Persistence of metadata
Metadata contains: application owner, service id (if related to a service), recipient address, and number of messages (only relevant for sms) 

Metadata is persisted until invoice for the data in question is completed. 

### Conclusion
For notifications related to an Altinn service, the contents of the notification will be available until the notification itself is deleted. 

The metadata is persisted at least until the invoice is sent out.

We do receive inquiries into if a notification was sent to a certain recipient, in Altinn 2 we can say what the recipient address was, but not who the recipient is. And only until the metadata is deleted.

Some metadata is required for invoicing, such as number of messages, service owner and which service the notification was linked to.

There are uncertainties into if the sanation jobs for Altinn II are currently running, but the analysis points to the intended architecture.

**Comment by SandGrainOne** [comment]
Looks right, no surprises.
