### ISSUE TITLE
Build first version of Notifcation component

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-notifications#3]
## Description

As part of the hackathon, we will build and deploy the first version of the notification component. This is based on some of the functional and technical requirements from #1 

**Bonus Targets**
- Github Actions for build and deploy and code analysis
- .Net 6
- New project structure
- Separate repo
- Future proof
- Test Visual Studio 2022

### Components

In the future, we might need to split notification components into more than one but for this hackathon we will only establish the Platform Notification component. 

**Hackaton Decision** Build only one component.

![Compnents](https://raw.githubusercontent.com/Altinn/altinn-studio/feature/notificaiton-analysis/doc/Notification.svg)

### Notification storage

We need to store notifications in separate storage. Since we need to support search by time PostgreSQL is chosen as database

**Hackaton decision** We use PostgreSQL

We need to design the data model in PostgreSQL

### Notifcation timer job

We need some jobs to identify and send messages 

Should we use a timer job to check DB for not sent messages? 

Should we use some queue? 

### Notification API

In Altinn 2 the notification is added to reportee elements when creating instances. 

This limited flexibility.

For the hackathon, all notifications need to be added as a separate call to the notification component API. 

This call will contain
- reference to an instance (optional in the future for standalone notification)
- criteria to send (always, instancenotchangedAfter, instanceNotCompleted)

The API needs to require an ORG authentication token and API will in the first version verify that org is the org for the instance. 

### Adress lookup

For the full functionality, the Notification component would need to support

- Looking up address for instance owner from KRR
- Looking up address for a unit profile from KoFuVi
- Looking up addresses for a personal unit profile from Altinn
- Using submitted email/phone numbers

**Hackaton decision**  We will only support looking up emails from profiles where an instance owner is a person or from supplied email address as part of the notification

Notification types 

- We should support that email and SMS 

### Message size

We need to decide what kind of limitation should we have on message size

Should we support long HTML emails?

### Multiple receivers

Notification should be able to support multiple receivers (endpoints identified with SMS/email)

### Email server

- Sendgrid, own email server in platform cluster, or digidir email server? 
- Other?

### Ops requirements

- Notification is deployed from a separate Repository 
- Github pipeline or Azure Pipeline?
- .Net 6 or .Net 5?

## Acceptance criteria

- [x] Notifcation component deployed to AT
~~- [ ] Email component deployed to AT (if separate)~~

## Specification tasks

- [x] Development tasks are defined

## Development tasks
- [x] Create new repository for Altinn Notifications
- [x] Create empty .Net 6 web application and add to repostory
- [x] Setup build pipeline for .Net component
- [x] Setup deploy pipeline for .Net componet
- [x] Create Functions project for Notifications componet
- [x] Create build pipeline for functions project
- [x] Create deploy pipeline
- [x] Implement API for sending notifications for external
- [x] Implement API for finding notifications to send
- [x] Implement API for pushing notifcations
- [x] Define datamodell and datastorage
- [x] Setup database for Notifications
- [x] Create schemas and tables
- [x] Setup deploy of database
- [x] Setup API management

**Comment by acn-sbuad** [comment]
First version built during hackaton. Remaning functionality is covered by new issues
