### ISSUE TITLE
Make an endpoint for getting delivery report with basic auth with IP filter

### ISSUE THREAD

**Issue by codemascot** [Altinn/altinn-notifications#377]
## Description
Need an endpoint for for receiving the SMS delivery reports from Link Mobility

## Consideration
This issue is closely connected with #376 , so keep an eye on this issue while working on this.

## Tasks
- [x] Need to introduce the API endpoint
- [x] Implement basic authentication for the endpoint
~~- [ ] Implement IP filtering for the API endpoint. Means make sure the endpoint only receives requests from certain IP address which are whitelisted by us. And the list of white listed IP address will be provided by Link Mobility or they are mentioned in the Link Mobility documentation.~~

## Acceptance Criteria
- There should be an endpoint to post the delivery status.
- The endpoint should have basic authentication enabled.
~~- IP filtering should work or necessary IPs should be whitelisted.~~

**Comment by acn-sbuad** [comment]
Verified in TT
