### ISSUE TITLE
Delivery report update need to be sent back to Kafka message queue

### ISSUE THREAD

**Issue by codemascot** [Altinn/altinn-notifications#378]
## Description
Need to send the SMS delivery report to `altinn-notifications` application to be stored with associated SMS.

## Consideration
The Kafka Producer needed for this issue will be covered in the issue #369 , so keep an eye on this issue #369 while working on this issue. 

## Tasks
- [x] Write the functionality to send the delivery report to Kafka topic to send to notification application to be saved in the DB with associated SMS ID.

## Acceptance Criteria
Kafka message queue should receive an update about the delivery report from SMS notification application Kafka producer.

**Comment by acn-sbuad** [comment]
Verified in TT
