### ISSUE TITLE
Handle environment connections between Altinn and LinkMobility

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#426]
### Description
How to use LinkMobility test environments in different Altinn environments.

Possible solutions:
- Production account in TT02?
    - No! Test account with whitelisting of phone numbers
- Unique account for TT02, but nothing in AT?
- Unique account for TT02, One shared in AT?
- Different test accounts for different environments?

### Acceptance criteria
- [x] Documentation is updated with the conclusion

**Comment by acn-sbuad** [comment]
AT, YT, TT share a gateway for now. [Documentation availble](https://docs.altinn.studio/notifications/architecture/sms/#link-mobility)
