### ISSUE TITLE
Add support for picking Altinn 3 App when adding personal contact information associated with an organisation

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#470]
### Description
It must be possible for users to see and select Altinn 3 App when desciding  which appservice to get notifications for when adding personal contact information associated with an organisation.

Altinn 3 apps should be included in the list:
![image](https://github.com/Altinn/altinn-notifications/assets/2217340/81c64fb9-d641-4b53-b730-d8c2e62438e0)

- Identify how to obtain a list of Altinn 3 apps that should be included in the list of available services
     - We can see Altinn 3 apps through the **Ask for accesss** page in Altinn 2
     - GetAvailableServices can already include Altinn 3 Apps with correct input flags and search parameters.
- Perform a merge of the Altinn 3 apps into the existing list being displayed to the user
     - Expand the return type of https://tt02.altinn.no/ui/AccessManagement/NotificationServiceSearchJson/
- Identify how to store the id of an Altinn 3 app together with the "contact point"
- Identify all code points in Altinn 2 where contact points associated with an Altinn 3 app is ignored-removed before use in notifications
- Expand table ServiceNotificationOptionForReportee with a new property for resource or app id.
-

**Comment by acn-sbuad** [comment]
Verified in AT24. 
Possible to both select and deselect A3 apps + 2.0 services. 
A3 apps are searcheable both by appId and title
