### ISSUE TITLE
Add notification channels SmsPreferred and EmailPreferred

### ISSUE THREAD

**Issue by acn-sbuad** [Altinn/altinn-notifications#541]
### Description

Service owners may be flexible w.r.t which notification channel is used to pass on a notification. 
If this is the case they can prefer one channel, but be fine with the notification being sent via backup channel if required. 

`SmsPreferred` will send an sms to the recipient if a mobile number is available, and an email if no mobile number is available, but an email address is. 

### Considerations
- If we cannot find neither an email address nor a mobile number should we create a notification within just the preferred notification channel which gets the status recipient not identified ? 
    - Refinement: We will store the result on a notification on the preferred channel.
- Given a new notification channel, how do we ensure that service owners get the best view of the final result? We have the endpoints `/notifications/sms` and `notifications/email` but they would need to call both and cross check the lists to identify who has and has not received notifications. 
    - Refinement: Deferred, we postpone this question to when we start getting questions or feature requests.
- How do we handle the case where notification channel is SmsPreferred and a recipient is provided with national identity number + an email address? Do we use provided email directly, look up sms and if no number present utse the registered or provided email ? 
    - Refinement: Orders where a single recipient have both a lookup value and a specific contact point should be refused.
    
- When sending notification to org, if we find a set of emails for emailPreferred, do we not send sms to the users that only have a number registered? In other words, is emailPreferred evaluated for each eligible recipient, or for the organization as a whole? 

#### Notifications

- [x] Add new enum values to `NotificationChannelExt`
- [x] Add new endpoint to OrdersController for ordering notifications with any notification channel
- [x] Add new RequestValidator, if a "preferred" notification channel is used, both templates must be populated.
- [x] Consider if any changes is required t othe external models or status models. 

#### Notifications.Core
 __Persisting the order request__
 - [x] Re-work logic in OrderRequestService.GetRecipientLookupResult to handle the case where the new notification channels are used. 
 - [x] Add function to ContactPoint service for AddPreferedContactPoints which can handle both SmsPrefered and Email Prefered. 
 - [x] Re-work logic for defining RecipientLookupResult given the new notification channel

 __Processing the order__

- [x] Add a new interface and service for AdvancedOrderProcessing /ComplexOrderProcessing which is able to handle both SmsPreferred and EmailPreferred processing logic. Interface should define the same methods as `IEmailOrderProcessingService`

#### Notifications.Tests

- Implement relevant tests for the service layer as unit tests wherever integrations are involved.
- 
#### Notifications.IntegrationsTest
- Implement relevant tests validating the validation logic in the controller

#### Chores
- [x] Update APIM 
- [x] Update swagger in docs
- 
#### Documentation
- [x] User guide on the new endpoint
- [x] Document the new notification channel wherever relevant

### Acceptance Criterias
- [x] It is possible to place a notification order using `SmsPreferred` as the notification channel
- [x] It is possible to place a notification order using `EmailPreferred` as the notification channel
- [x] It is possible to place a notification order using `Sms` as the notification channel
- [x] It is possible to place a notification order using `Email` as the notification channel
- [x] If a preferred notification channel is defined and the recipient does not have any contact points, the lookup should fail
- [x] If SmsPreferred has been defined as the notification channel and the recipient only has an email address registered, an email notification should be sent
- [x] If EmailPreferred has been defined as the notification channel and the recipient only has a mobile number registered, an sms notification should be sent
- [x] Orders where a single recipient have both a lookup value and a specific contact point should be refused.
- [x] If user is reserved, no communication channel should be used

**Comment by SandGrainOne** [comment]
Doing some initial testing and have found a tiny issue: Looks like we have a fallback to `Email` notification also when given channel is `Sms`. This is not expected. The expected result would be to fail with missing contact information.

**Comment by SandGrainOne** [comment]
All tasks completed.
