### ISSUE TITLE
Investigate use of the email address keyword

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#604]

**Comment by HenningNormann** [comment]
@acn-sbuad 
`SELECT count(*) FROM [ServiceEngine].[Notification].[NotificationTemplate] where NotificationText like '%$reporteeEmail$%' `

gir 0 i prod

**Comment by acn-sbuad** [comment]
Given Hennings comment we should be good to reject email addresse i text. Suggest we close this issue

**Comment by SandGrainOne** [comment]
Henning did also look for the mobile number macro. This also returned 0 texts.
