### ISSUE TITLE
Getting success response with error message

### ISSUE THREAD

**Issue by SandGrainOne** [Altinn/altinn-notifications#608]
### Description of the bug

It's possible to craft a request against the `notifications/api/v1/orders` endpoint where the response is 202 ok, but the immediate response is Failed where missingContact array contains a null entry. See examples:

Request:
```json
{
    "notificationChannel": "Sms",
    "smsTemplate": {
        "body": "Hei Du har en ny melding i Altinn."
    },
    "sendersReference": "{{$guid}}",
    "recipients": [
        {
            "mobileNumber": "+4793427384"
        }
    ]
}
```

Response:
```json
{
    "orderId": "e0cf08c8-fe19-47d9-8e26-c03b1fea9ce5",
    "recipientLookup": {
        "status": "Failed",
        "isReserved": [],
        "missingContact": [
            null
        ]
    }
}
```

### Steps To Reproduce

Use Postman or similar testing tool to send the example request and observe the response.

**Comment by Ahmed-Ghanam** [comment]
I get the following expected result when testing using Postman:
```
{
    "orderId": "54bac053-ad8b-4589-ad6f-a8d28c473258"
}
```

**Comment by Ahmed-Ghanam** [comment]
I tested both the Email and SMS channels, and the response returned only the order identifier when provided with valid input data.
