### ISSUE TITLE
Invalid characters allowed in mobileNumber Field of /notifications/api/v1/orders Endpoint

### ISSUE THREAD

**Issue by Ahmed-Ghanam** [Altinn/altinn-notifications#619]
### Description

The `POST /notifications/api/v1/orders` endpoint does not properly handle invalid characters in the `mobileNumber` field. For example, submitting a value like `"+47invalidChar"` results in an internal server error (500) without providing a meaningful error message to the user.

### Steps to Reproduce
1. Send a `POST` request to the `/notifications/api/v1/orders` endpoint with a `mobileNumber` field containing invalid characters (e.g., `"+47invalidChar"`).
2. Observe that the API responds with an internal server error (500) instead of rejecting the request with a meaningful validation error message.
   
#### Example Request:
```json
{
    "notificationChannel": "Sms",
    "smsTemplate": {
        "senderNumber": "+4746269164",
        "body": "Hei, Du har en ny melding i Altinn."
    },
    "sendersReference": "907c8054-b2cc-4dca-b4df-c95b89860762",
    "recipients": [
        {
            "mobileNumber": "+47invalidChar"
        }
    ]
}
```

### Expected Behavior
The API should validate the `mobileNumber` field to ensure it adheres to valid international phone number format standards. If invalid characters are submitted, the API should reject the request with a descriptive error message, such as "Invalid mobile number format," preventing further processing.

  
### Suggested Fix
Introduce or improve input validation on the `mobileNumber` field to ensure it only accepts valid numeric characters following international phone number standards. When validation fails, return a clear and informative error message, rejecting the request before it reaches internal processing.

### Acceptance criteria:

- [ ] Validation-scheme documented at docs.altinn.studio
- [ ] Failed validations give response-code 400 and a message (e.g. "mobileNumber format not adhering to...")

**Comment by olebhansen** [comment]
Updating issue to be "adhere to validation standard + document this", to avoid confusion on permitted content. Feiled validations should give 400 and a sensible message.

See: https://altinn.slack.com/archives/C069J71UQCQ/p1727789663181299?thread_ts=1727703986.978639&cid=C069J71UQCQ

> Skjønner, siste klarering da: Jeg får 400 bad request på visse telefonnumre og formater, kan du si hvilken standard dere bruker for å validere gyldige numre?
Ut ifra testingen min så virker det til å være E.164

**Comment by hggutvik** [comment]
Our initial guess was correct - the 500 error results from the validation package not handling the letters
![Image](https://github.com/user-attachments/assets/a75d617f-d3fa-4278-862f-d8c62f89704e)

**Comment by SandGrainOne** [comment]
Manual tests performed and changes approved.
