### ISSUE TITLE
Integrate with profile

### ISSUE THREAD

**Issue by TheTechArch** [Altinn/altinn-notifications#9]
## Description
We need to integrate with profile to get the addresses from KRR when sender does not have them

## Development task
- [x] Create client to call profile. 
- [x] Configure access token usage from notification to profile (Partially completed)
- [x] Add code to find address when not provided from sender (Moved to new issue)

The last task is moved to a new issue: #22

**Comment by SandGrainOne** [comment]
We've implemented a client to get a UserProfile from the Profile component. One method with UserId and another with "SSN" - National identity number. 

The Client will require an IAccessTokenGenerator to get an AccessToken and an IUserTokenProvider to get the user token before submitting the request. Both have implementations, but neither has been added to the ServiceProvider. Some additional configuration might be needed.

The test coverage in the Integration project is currently 74%. On new code it is close to 90%
